server:
  port: 8080
  

eureka: 
  instance: 
#     hostname: nriet-datacenter-api
    instance-id: nriet-datacenter-api
    prefer-ip-address: true
    ip-address: 172.16.50.224
    metadata-map: 
      user.name: user
      user.password: ${CONFIG_SERVER_PASSWORD:password}
  client: 
    service-url: 
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@172.16.4.52:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.4.51:13306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate: 
      naming: 
        physical-strategy: com.nriet.datacenter.config.MySQLUpperCaseStrategy
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
security:
  user:
    name: user
    password: password
  oauth2:
    resource: 
      userInfoUri: http://172.16.4.52:8060/uaa/current
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://172.16.4.52:8060/uaa/oauth/token
      grant_type: password
      scope: read%20write
      clientAuthenticationScheme: header