server:
  port: 8120
spring:
  thymeleaf:
    prefix: classpath:/static/html/
    suffix: .html
    cache: false
    mode: HTML5
    encoding: utf-8
    content-type: text/html
  cloud: 
    bus: 
      trace: 
        enabled: true
management: 
  security: 
    enabled: false
eureka: 
  instance: 
#     hostname: nriet-datacenter-api
    instance-id: 172.16.50.224:8120
    prefer-ip-address: true
    ip-address: 172.16.50.224
    metadata-map: 
      user.name: user
      user.password: ${CONFIG_SERVER_PASSWORD:password}
  client: 
    service-url: 
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@172.16.4.52:8761/eureka/
      
queryUrl: 
  loginUrl: http://172.16.4.52:8060/manage/validate/{name}/{password}
  ctx: http://localhost:8060
  testUrl: http://localhost:1111
  
security:
  user:
    name: anil
    password: password
  oauth2:
    resource: 
      userInfoUri: http://172.16.4.52:8060/uaa/current
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://172.16.4.52:8060/uaa/oauth/token
      grant_type: password
      scope: read%20write
      clientAuthenticationScheme: header