server:
  port: 8888

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangxd1989/spring-boot-cloud
          search-paths: config-repo
  rabbitmq:
    host: 172.16.50.224
    username: admin
    password: 123456
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
authserver:
    hostname: auth-service
    port: 5000
    contextPath: /uaa
mysqlserver:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.4.51:13306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
